//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.13 at 01:43:11 PM CEST 
//


package mt102;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mt102 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mt102">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/mt102}zaglavljeMt102"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/mt102}pojedinacnoPlacanjeMt102"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mt102", propOrder = {
    "zaglavljeMt102",
    "pojedinacnoPlacanjeMt102"
})
public class Mt102 {

    @XmlElement(required = true)
    protected ZaglavljeMt102 zaglavljeMt102;
    @XmlElement(required = true)
    protected PojedinacnoPlacanjeMt102 pojedinacnoPlacanjeMt102;

    /**
     * Gets the value of the zaglavljeMt102 property.
     * 
     * @return
     *     possible object is
     *     {@link ZaglavljeMt102 }
     *     
     */
    public ZaglavljeMt102 getZaglavljeMt102() {
        return zaglavljeMt102;
    }

    /**
     * Sets the value of the zaglavljeMt102 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZaglavljeMt102 }
     *     
     */
    public void setZaglavljeMt102(ZaglavljeMt102 value) {
        this.zaglavljeMt102 = value;
    }

    /**
     * Gets the value of the pojedinacnoPlacanjeMt102 property.
     * 
     * @return
     *     possible object is
     *     {@link PojedinacnoPlacanjeMt102 }
     *     
     */
    public PojedinacnoPlacanjeMt102 getPojedinacnoPlacanjeMt102() {
        return pojedinacnoPlacanjeMt102;
    }

    /**
     * Sets the value of the pojedinacnoPlacanjeMt102 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PojedinacnoPlacanjeMt102 }
     *     
     */
    public void setPojedinacnoPlacanjeMt102(PojedinacnoPlacanjeMt102 value) {
        this.pojedinacnoPlacanjeMt102 = value;
    }

}
